### ISSUE TITLE
Error on client disconnect at module NET

### ISSUE THREAD

**Issue by simaodeveloper** [simaodeveloper/node_labs#1]
### Informations

``` javascript

title: 'npm',
version: 'v6.9.1',

{
     versions: { 
          http_parser: '2.7.0',
          node: '6.9.1',
          v8: '5.1.281.84',
          uv: '1.9.1',
          zlib: '1.2.8',
          ares: '1.10.1-DEV',
          icu: '57.1',
          modules: '48',
          openssl: '1.0.2j' 
     },
  arch: 'x64',
  platform: 'win32'
}

```

##### server.js

``` javascript
var net = require('net');

var connections 	= [];
var broadcast 	= function(message, origin) {
	connections.forEach(function(connection) {
		if (connection === origin) return;
		connection.write(message);
	});
};

net.createServer(function(connection) {
	connections.push(connection);
	
	connection.on('data', function(message) {
 		var command = message.toString();
 		if(command.indexOf('/nickname') === 0) {
 			var nickname = command.replace('/nickname ', "");
 			broadcast(connection.nickname + 'is now' + nickname);
 			connection.nickname = nickname;
 			return;
 		}
 		broadcast(connection.nickname + ' > ' + message, connection);
	});

	connection.on('end', function() {
		broadcast(connection.nickname + 'has left', connection);
		connections.splice(connections.indexOf(connection), 1);
	});
}).listen(3000);
```

##### client.js

``` javascript
var net 	= require('net');
var client	= net.connect(3000);

client.on('connect', function() {
	client.write('Hello, I am the client!');
});

client.on('data', function(message) {
	 console.log(message.toString());
});

client.on('end', function() {
	process.exit();
});

process.stdin.on('readable', function() {
	var message = process.stdin.read();

	if(!message) return;

	message = message.toString().replace(/\n/, '');

	client.write(message);
});
``` 

#####  error client

``` javascript
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)

```

##### error server

``` javascript
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)

```

**Comment by simaodeveloper** [comment]
@rodrigobranas estou pesquisando o que seria a causa deste erro quando um dos clientes se desconecta, consegue me ajudar?

**Comment by simaodeveloper** [comment]
Não o porque esta ocorrendo este erro, mas consegui reproduzir o seu exemplo adicionando uma captura de erro no socket via server.

``` javascript
connection.on('error', function() {
	broadcast(connection.nickname + 'has left', connection);
	connections.splice(connections.indexOf(connection), 1);
);
```
